### PR TITLE
add slot key

### PR DESCRIPTION
**Pull request by yibuyisheng**
The `resolveSlots` method in VUE has a `if` condition: https://github.com/vuejs/vue/blob/684cd7d21aa7cb9a40fb4a8542c4e08fb3801a86/src/core/instance/render-helpers/resolve-slots.js#L24

So we should add slot key for slot vnodes.

### CODE REVIEW

**Comment by yibuyisheng** [comment]
@jackmellis I made a demo here: https://jsfiddle.net/2by06fvt/1/ .

The problem is using the `template slot`.

In VUE's `resolveSlots` method, it checks `template` tag and use it's children as the slot: https://github.com/vuejs/vue/blob/684cd7d21aa7cb9a40fb4a8542c4e08fb3801a86/src/core/instance/render-helpers/resolve-slots.js#L29 .

**Comment by jackmellis** [comment]
Yes I think I understand what problem this is solving (many thanks btw). But I would like to have these solutions fully unit tested so there is an audit of all of the handled scenarios within the codebase.

**Comment by yibuyisheng** [comment]
OK, I'll find a time to add some unit tests.

**Comment by jackmellis** [comment]
Thanks dude

**Comment by yibuyisheng** [comment]
@jackmellis I found that the `vuenit` uses `vue.rumtime.common.js`, so in the test runtime, it dose not have a template compiler.

But I do not find out why the previous `Component`s in test codes do not cause exceptions.

**Comment by jackmellis** [comment]
Because Vuenit also uses `vue-template-compiler` to compile the templates before mounting them

**Comment by yibuyisheng** [comment]
But my tests still get these errors:

image

**Comment by jackmellis** [comment]
Ah I think I get it.

**Comment by jackmellis** [comment]
Could you add
```js
mount(Component)
```
to line 11 of the test file.

It's a little bit of a hack but it should work.

**Comment by yibuyisheng** [comment]
```
Could you add

mount(Component)
to line 11 of the test file.

It's a little bit of a hack but it should work.
```

It works.

**Pull request merged**
